name: Build Spring Boot Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: ./Pos-Backend
        run: mvn clean install -DskipTests

      - name: Build Docker Image
        run: docker build -t backend-image ./Pos-Backend
